---
title: "Group 3 Project"
authors: "John C. Hale, Leonard Clinton"
date: "November 20, 2019"
output: html_document
---

```{r}
#install.packages("MVA")
library(MVA)
library(dplyr)
```

### Read in Data
```{r}
options( warn = -1, width = 160 )
census <- read.csv("../data/cleaned_census_data.csv")
head(census)
options(digits = 3)

```

### Correlation Matrix
```{r}
cor <- cor(census)
cor[,2:13]
```
```{r}
cor[,14:23]
```
```{r}
d = dist(census)
census.s = scale(census, center=TRUE)
#d.s = dist(census.s)
#round((d.s), 2)
Boxplot(census.s, id.method="y")
```
Common outliers are 8, 12, 6, 3,


```{r}
bvbox(census[,2:3],type = "n",
     xlab = "Agriculture",
     ylab = "Mining",
     pch = 5)
text(census[,2:3], cex = 0.8, label = census[,1],pch=10)
```

```{r}
bvbox(census[,11:12],type = "n",
     xlab = "IT",
     ylab = "Finance",
     pch = 50)
text(census[,11:12], cex = 0.8, label = census[,1],pch=10)
```
```{r}
plot(density(census$Population, bw = 1, kernel ="optcosine"))

```

```{r}
census_pca <- princomp(census[,2:23], cor = T)

summary(census_pca, cor=T, loadings = T)
```




```{r, dpi=300, fig.width=15, fig.height=8}
biplot(census_pca$scores[,1:2], census_pca$loadings[,1:2],col=c("black", "red"), cex = 0.6)
```

### a) Create a scaled distance matrix for observation.
```{r}
census.mds = cmdscale(dist(scale(census)), eig = T) 
cumsum(census.mds$eig)/sum(census.mds$eig)
```

### b) Perform Graphical MDS on Distance Matrix
```{r}
census.mds = cmdscale(dist(scale(census)), eig = T) 
 
eignv <- abs(census.mds$eig) 
 
plot(census.mds$points[,1:2], pch = ".")
text(census.mds$points[,1:2], labels = census$Region, cex = 0.6) 
```

### c) Convert Correlation Matrix to Distance
```{r}
#install.packages("psych")
library(psych)
census.cor = cmdscale(cor2dist(cor(census[,2:23])),eig=T)
census.cor
```


### d) Plot Correlation "Distance" Matrix
```{r}

eignv <- abs(census.cor$eig) 
 
plot(census.cor$points[,1:2], pch = ".")
text(census.cor$points[,1:2], labels = colnames(census[,2:23]), cex = 0.55)

```











